# Site settings

lang: en-GB
title: Lunar Transmissions
email: dach.bartlomiej@gmail.com
description: >- 
    A programming blog.
    Mostly musings on software architecture and design.
url: "https://bdach.github.io/"
author:
    name: Bartłomiej Dach
    picture: "/assets/images/me.jpg"
github_username: bdach

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
repository: bdach/bdach.github.io

# Pagination
paginate: 8
paginate_path: /page:num/

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  # turning these off for now. may bring back later if necessary
  - about.md
  - curriculum_vitae.md
